### ISSUE TITLE
Passing own arguments

### ISSUE THREAD

**Issue by shaggybb** [czunker/check_selenium#1]
Hi czunker!!

First of all, thank you for your effort and sharing the project. 

I have run a test in my nagios and it works well, but I would like to pass some args to my own class. Will the project support this kind of actions in the future?

Congratulations for your project.

**Comment by czunker** [comment]
Thanks.

Till now I had no need, passing arguments to the test.
I'll take a look at this.

On Thu, Jul 26, 2012 at 1:58 PM, shaggybb <
reply@reply.github.com

**Comment by finsterwalder** [comment]
What do you want to do? What would you use parameters for?

I currently only read a property file in my tests.
That allows me to configure my test execution.
I also had no need to pass any arguments from Nagios so far.
You could probably also use system properies, which you can pass to the JVM via "-D".
The underlying JUnit framework, which actually executes the tests, does not really allow passing parameters.

**Comment by shaggybb** [comment]
@finsterwalder, to solve the problem, I did the next steps:

1.- Getting arguments from command line via org.apache.commons.cli
2.- Passing arguments in startTest method to my test class through System.setProperty 
3.- Retrieving passed arguments by System.getProperty in my Test class.
