### ISSUE TITLE
build.xml basedir=bin

### ISSUE THREAD

**Issue by Djeezus** [czunker/check_selenium#3]
'lo,

I thought I'd just mention that the build.xml refers to ${bin} from where to jar ... that should be ${src} ofcourse :)

grtz,
gert

**Comment by Djeezus** [comment]
disregard the above,
it seems the build.xml does not include any "compile" section, after adding that and the dependency in "jar" target, everything is fine :)

grtz,
gert

**Comment by czunker** [comment]
hi gert,

would you mind sharing your additions to the build.xml?
I'd like to integrate your modifications.

Christian

**Comment by Djeezus** [comment]
'lo Christian,

here you go :)  I couldn't get the git diff post formatted in this comment box, and since I'm working on implementing RemoteWebDriver into the project, I've forked one of my own ... the build.xml is going to be  there :)

build tested with ant-1.8 :

id823933@BGC-BE-DD05A45C /cygdrive/c/Data/Downloads/check_selenium-master_finsterwalder/check_selenium-master
$ ant -f build_gert.xml
Buildfile: C:\Data\Downloads\check_selenium-master_finsterwalder\check_selenium-master\build_gert.xml

compile.info:
    [javac] C:\Data\Downloads\check_selenium-master_finsterwalder\check_selenium-master\build.xml:61: warning: 'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds
    [javac] Compiling 1 source file to C:\Data\Downloads\check_selenium-master_finsterwalder\check_selenium-master\bin
    [javac] C:\Data\Downloads\check_selenium-master_finsterwalder\check_selenium-master\build.xml:64: warning: 'includeantruntime' was not set, defaulting to build.sysclasspath=last; set to false for repeatable builds
    [javac] Compiling 2 source files to C:\Data\Downloads\check_selenium-master_finsterwalder\check_selenium-master\bin
    [javac] Note: C:\Data\Downloads\check_selenium-master_finsterwalder\check_selenium-master\src\com\example\tests\GoogleSeleniumTestCase.java uses or overrides a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.

jar:
      [jar] Building jar: C:\Data\Downloads\check_selenium-master_finsterwalder\check_selenium-master\dist\lib\selenium-example-tests.jar
      [jar] Building jar: C:\Data\Downloads\check_selenium-master_finsterwalder\check_selenium-master\dist\lib\check-selenium.jar

dist:
     [copy] Copying 11 files to C:\Data\Downloads\check_selenium-master_finsterwalder\check_selenium-master\dist\lib
      [tar] Building tar: C:\Data\Downloads\check_selenium-master_finsterwalder\check_selenium-master\check_selenium.tar.gz

BUILD SUCCESSFUL
Total time: 3 seconds

**Comment by czunker** [comment]
integrated with 1d04712bfd
