### ISSUE TITLE
webdriver

### ISSUE THREAD

**Issue by leddy-c3** [czunker/check_selenium#4]
Any idea what it would take to get this working with webdriver? Rewrite or minor tweaks?

As is, a webdriver-based test opens the browser, but then hangs.

**Comment by czunker** [comment]
Hi leddy-c3,

the code I've written just calls a specified testcase. My code doesn't contain any reference to the webdriver or the driver used before selenium 2.x.

The source code also contains a testcase with google.com using the webdriver and it worked for me.

Have you tried your testcase outside my nagios plugin?
Perhaps your testcase needs a newer version of the libaries. Please try to rebuild my plugin with a library version working for your testcase.

Christian
